### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by luop21** [OronzoD/STAR-MoorDyn-Coupling#1]
Can you show your paper DOI, your doc did not show The Doi link.

**Comment by OronzoD** [comment]
Unfortunally i do not have a doi yet, my paper is still under review. i have completed the first review and i am confident that it will be published soon. Sorry for the late answer but i do not use a lot git hub and i did not notice the comment. If you want you can check the status of the paper at https://track.authorhub.elsevier.com/?uuid=a5869f01-6875-4686-af0d-01f567ef9457.

**Comment by OronzoD** [comment]
The paper has been accepted and the journal is now finalising the paper. Soon it will be available!

**Comment by OronzoD** [comment]
Are you trying to compile it on windows?

**Comment by luop21** [comment]
yes, I try to compile it on windows, but it never success. I try your code, and i met this problem.

PS C:\Users\luop21\Desktop\STAR-MoorDyn-Coupling-main\STAR-MoorDyn-Coupling-main\Library> make
g++ -DDOUBLE_PRECISION -fPIC -shared -ldl Coupling/uclib.cpp MoorDyn-master/compileSO/MoorDyn.o MoorDyn-master/compileSO/Line.o MoorDyn-master/compileSO/Connection.o MoorDyn-master/compileSO/Misc.o MoorDyn-master/compileSO/kiss_fft.o -o test.so
D:\Program Files\CLion 2024.1.4\bin\mingw\bin/ld.exe: cannot find -ldl: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:12: comp] Error 1

**Comment by luop21** [comment]
if I delete **-ldl** in makefile,  the error is "undefined reference to `__imp_ucfunc'" and "undefined reference to `__imp_ucarg'"

**Comment by luop21** [comment]
So what can I do to solve this problem, please help me!

**Comment by OronzoD** [comment]
I have never tried to compile it on windows. I can try to look into it and find a solution, but i can do it only today since tomorrow I’m leaving for my holiday. I’ll let you know what i can achieve.

**Comment by OronzoD** [comment]
Firstly i think that you need to compile MoorDyn for windows, so you need to use the make file that you can find in the compileDLL folder and not the makefile of the compileSO folder (This is all MoorDyn related and is not found in this repository). 
Secondly, the makefile for compiling this library only works on linux. I can try to write something that is working in both OS. i will create a new makefile. lets try working on that

**Comment by OronzoD** [comment]
I have changed my mind. I have created a Makefile specifically for Windows, called Makefile_Windows. I am currently testing it.

**Comment by OronzoD** [comment]
Unfortunately, I was not able to make it work for now, and tomorrow I am leaving for vacation. I will look into it in the first days of September when I come back.

**Comment by luop21** [comment]
thank you very much

**Comment by luop21** [comment]
I try it for several days, and now I will try it in Linux system,I download  a virtual machine

**Comment by OronzoD** [comment]
let me know if you managed to compile it!

**Comment by OronzoD** [comment]
if you have further problems compiling the library, i suggest you open a new issue, so if someone encounter the same problem can look into that. I want to close this issue as soon as i get the DOI of my paper.

**Comment by luop21** [comment]
Ok

**Comment by OronzoD** [comment]
> Can you show your paper DOI, your doc did not show The Doi link.

The paper has now been accepted. I have edited the readme with the link to the paper and the doi. Since it is too soon, the doi does not work yet. I think in a couple of days it will work just fine, but just to be sure I will leave this issue open untill the doi is working.

**Comment by luop21** [comment]
OK， I get it!  Congratulations!
