### ISSUE TITLE
Error:dtC is less than dtM. (0.02 < 0)    Error:SIGSEGV:memory access exception

### ISSUE THREAD

**Issue by luop21** [OronzoD/STAR-MoorDyn-Coupling#2]
(1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c)
Matt Hall,licensed under GPL v3.
Error:unable to open lines.txt file

(2)Error:dtC is less than dtM. (0.02 < 0)    Error:SIGSEGV:memory access exception

now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0)    Error:SIGSEGV:memory access exception. 

Do you have met these errors? and how to solve it?

**Comment by luop21** [comment]
![image](https://github.com/user-attachments/assets/0d4af31c-23e7-4df7-aea4-c8d8faf2478f)

**Comment by OronzoD** [comment]
Hi, I am glad you did manage to compile the library. What is your time step in star and in Moordyn? (you define the time step in the lines files)
The moordyn dt should be less or equal to star dt (preferably a multiple). Let me know if this is the cause of the problem!

**Comment by luop21** [comment]
I use  the star file you load and lines.txt file you load. I changed  the parameters in uclib.cp. 
[lines.txt](https://github.com/user-attachments/files/16691602/lines.txt)

**Comment by luop21** [comment]
Should I need to change
	char cwd[1024];
	chdir("/path/to/change/directory/to");
	getcwd(cwd, sizeof(cwd));
the path of lines.txt
You mean that only in the Mooring folder, the lines.txt can ben read?

**Comment by OronzoD** [comment]
Yes, the lines file should be located inside the Mooring folder, otherwise it will not be read by the library

**Comment by OronzoD** [comment]
Also if you are using the template I provided, remember that just for rapidity the base size of the simulation is not 100 (the supposed base size) but 200 or 300, I cannot remember right now.

**Comment by luop21** [comment]
I mean I succeed. thank you very much. Have a good vocation!

**Comment by OronzoD** [comment]
Perfect! Happy to hear that

**Comment by HITSC30** [comment]
> (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> 
> (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> 
> now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> 
> Do you have met these errors? and how to solve it?

Hi bro, i am doing the same work like what u have done these days.  I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows.
1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. 
cc1plus.exe: fatal error: main.c: No such file or directory
compilation terminated.
make: *** [makefile:14: main] Error 1
I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp

**Comment by HITSC30** [comment]
> > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > Do you have met these errors? and how to solve it?
> 
> Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp

I know why the fact happen, I just use the command "make". Then i carefully look up the readme.md file, i use the command "make makefile comp", but i also meet mistakes like below.
make: Nothing to be done for 'makefile'.
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x86c): undefined reference to `__imp_ucfunc'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x896): undefined reference to `__imp_ucarg'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8c0): undefined reference to `__imp_ucarg'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8ea): undefined reference to `__imp_ucarg'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x914): undefined reference to `__imp_ucarg'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x93e): undefined reference to `__imp_ucarg'
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x968): more undefined references to `__imp_ucarg' follow
D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x9b6): undefined reference to `__imp_ucfunc'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:16: comp] Error 1
I am a rookie in the region. I look forward for your reply on how it works. 
Wish a good day for all you！

**Comment by OronzoD** [comment]
> > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > Do you have met these errors? and how to solve it?
> 
> Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp

Hi,

I haven’t completed the Windows coupling yet. The Makefile for Windows is just an attempt; unfortunately, I don’t have much experience with compiling on Windows. Since many people have been asking about a Windows implementation, I’ll make an effort to get it working in the coming days!

**Comment by HITSC30** [comment]
> > > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > > Do you have met these errors? and how to solve it?
> > 
> > 
> > Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp
> 
> Hi,
> 
> I haven’t completed the Windows coupling yet. The Makefile for Windows is just an attempt; unfortunately, I don’t have much experience with compiling on Windows. Since many people have been asking about a Windows implementation, I’ll make an effort to get it working in the coming days!

Hello, friend:
Thank you very much for your reply.
I'm equally grateful for the open source work you've done, which has provided us with a framework for dealing with the MoorDyn coupling problem, as well as dramatically shortening the time it takes for us to get up to speed. A lot of people ask questions about windows, mostly for the same reason I did, some of the rookies like me, more familiar with windows. What's more, maybe they expect to complete basic testing on windows before submitting to a linux server for extensive computation.  Next, I will try to complete the related work under LINUX system, and expect to share with you if I have satisfactory results; and also expect to get your help if I encounter problems. Looking forward to your attempted work on windows and possible video tutorials.
Good luck with your work.

**Comment by HITSC30** [comment]
> > > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > > Do you have met these errors? and how to solve it?
> > 
> > 
> > Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp
> 
> I know why the fact happen, I just use the command "make". Then i carefully look up the readme.md file, i use the command "make makefile comp", but i also meet mistakes like below. make: Nothing to be done for 'makefile'. D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x86c): undefined reference to `__imp_ucfunc' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x896): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8c0): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8ea): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x914): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x93e): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x968): more undefined references to `__imp_ucarg' follow D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x9b6): undefined reference to `__imp_ucfunc' collect2.exe: error: ld returned 1 exit status make: *** [makefile:16: comp] Error 1 I am a rookie in the region. I look forward for your reply on how it works. Wish a good day for all you！

I use Linux(ubuntu) to compile the file. I just share somethings that i meet in the progrocess. Why i face the upper result, I use the command of "make" to compile, when i use "make makefile comp", it show me that fatal error: "Windows.h  No such file or directory  37| "include<Windows.h>".
I use MoorDyn with the version of MoorDyn-1.01.02. I try to solve the problem, it shows that <Windows.h> is a flie in windows system, i just see the MoorDyn.h. The useful code which i think as below:
#ifndef OSX
#ifndef LINUX
#include<Windows.h>
#endif
#endif
I think i use ubuntu system, the code "#include<Windows.h>" should't work. I will pay attention to solve the problem, just record interesting mistakes.
Wish a happy day for all U!

**Comment by s-zhang20** [comment]
> > > > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > > > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > > > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > > > Do you have met these errors? and how to solve it?
> > > 
> > > 
> > > Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp
> > 
> > 
> > I know why the fact happen, I just use the command "make". Then i carefully look up the readme.md file, i use the command "make makefile comp", but i also meet mistakes like below. make: Nothing to be done for 'makefile'. D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x86c): undefined reference to `__imp_ucfunc' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x896): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8c0): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8ea): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x914): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x93e): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x968): more undefined references to `__imp_ucarg' follow D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x9b6): undefined reference to `__imp_ucfunc' collect2.exe: error: ld returned 1 exit status make: *** [makefile:16: comp] Error 1 I am a rookie in the region. I look forward for your reply on how it works. Wish a good day for all you！
> 
> I use Linux(ubuntu) to compile the file. I just share somethings that i meet in the progrocess. Why i face the upper result, I use the command of "make" to compile, when i use "make makefile comp", it show me that fatal error: "Windows.h No such file or directory 37| "include<Windows.h>". I use MoorDyn with the version of MoorDyn-1.01.02. I try to solve the problem, it shows that <Windows.h> is a flie in windows system, i just see the MoorDyn.h. The useful code which i think as below: #ifndef OSX #ifndef LINUX #include<Windows.h> #endif #endif I think i use ubuntu system, the code "#include<Windows.h>" should't work. I will pay attention to solve the problem, just record interesting mistakes. Wish a happy day for all U!

@HITSC30 Thank you for sharing, I encountered the same problem as you ("Windows.h No such file or directory 37| "include<Windows.h>"), did you finally solve it? Could you share how you solved it?
Wishing you all success in your work!

**Comment by s-zhang20** [comment]
> > > > > (1)Running MoorDyn(v1.01.02C，2021-02-14)Copyright(c) Matt Hall,licensed under GPL v3. Error:unable to open lines.txt file
> > > > > (2)Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception
> > > > > now I can compile MoorDyn and uclib.cpp on LinuxOS platform. However, when I load my test.o. The output log shows the first Error: unable to open lines.txt file. When I try to run the StarCCM , the StarCCM file shows the second Error: Error:dtC is less than dtM. (0.02 < 0) Error:SIGSEGV:memory access exception.
> > > > > Do you have met these errors? and how to solve it?
> > > > 
> > > > 
> > > > Hi bro, i am doing the same work like what u have done these days. I also face some issures that you may face in last days. I sincerely ask one questions for you and the author. I use vscode to compile the file in the env of windows. 1.how do you complile the uclib.cpp in Coupling folder. When i compile it in the Library folder where makefile _windows file exists, it reminds me that occurs me the mistakes below. cc1plus.exe: fatal error: main.c: No such file or directory compilation terminated. make: *** [makefile:14: main] Error 1 I wan confused that there surely no main.cpp in the file and the third party in moordyn, how do you compile the uclib.cpp
> > > 
> > > 
> > > I know why the fact happen, I just use the command "make". Then i carefully look up the readme.md file, i use the command "make makefile comp", but i also meet mistakes like below. make: Nothing to be done for 'makefile'. D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x86c): undefined reference to `__imp_ucfunc' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x896): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8c0): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x8ea): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x914): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x93e): undefined reference to `__imp_ucarg' D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x968): more undefined references to `__imp_ucarg' follow D:/SoftWareInstall/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ccx\AppData\Local\Temp\ccLVxZ9V.o:uclib.cpp:(.text+0x9b6): undefined reference to `__imp_ucfunc' collect2.exe: error: ld returned 1 exit status make: *** [makefile:16: comp] Error 1 I am a rookie in the region. I look forward for your reply on how it works. Wish a good day for all you！
> > 
> > 
> > I use Linux(ubuntu) to compile the file. I just share somethings that i meet in the progrocess. Why i face the upper result, I use the command of "make" to compile, when i use "make makefile comp", it show me that fatal error: "Windows.h No such file or directory 37| "include<Windows.h>". I use MoorDyn with the version of MoorDyn-1.01.02. I try to solve the problem, it shows that <Windows.h> is a flie in windows system, i just see the MoorDyn.h. The useful code which i think as below: #ifndef OSX #ifndef LINUX #include<Windows.h> #endif #endif I think i use ubuntu system, the code "#include<Windows.h>" should't work. I will pay attention to solve the problem, just record interesting mistakes. Wish a happy day for all U!
> 
> [@HITSC30](https://github.com/HITSC30) Thank you for sharing, I encountered the same problem as you ("Windows.h No such file or directory 37| "include<Windows.h>"), did you finally solve it? Could you share how you solved it? Wishing you all success in your work!

My issue has been resolved. Wish everyone productive work!
